/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface IdatisButton {
        "disabled": boolean;
        "text": string;
    }
}
declare global {
    interface HTMLIdatisButtonElement extends Components.IdatisButton, HTMLStencilElement {
    }
    var HTMLIdatisButtonElement: {
        prototype: HTMLIdatisButtonElement;
        new (): HTMLIdatisButtonElement;
    };
    interface HTMLElementTagNameMap {
        "idatis-button": HTMLIdatisButtonElement;
    }
}
declare namespace LocalJSX {
    interface IdatisButton {
        "disabled"?: boolean;
        "text"?: string;
    }
    interface IntrinsicElements {
        "idatis-button": IdatisButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "idatis-button": LocalJSX.IdatisButton & JSXBase.HTMLAttributes<HTMLIdatisButtonElement>;
        }
    }
}
